name: Rolling Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build JAR
        working-directory: ./backend
        run: |
          chmod +x gradlew
          ./gradlew clean build

      - name: Upload to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./backend/build/libs/duri-0.0.1-SNAPSHOT.jar"
          target: "~/deploy/"

      - name: Deploy app1 (8081)
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/deploy
            bash deploy.sh app1
            curl -f http://localhost:8081/actuator/health

      - name: Deploy app2 (8082)
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/deploy
            bash deploy.sh app2
            curl -f http://localhost:8082/actuator/health
